version: "3.2"
services:
  api:
    container_name: api
    build: ./service
    volumes:
      - ./service:/api
    ports:
      - 5000:5000
    depends_on:
      - redis
  web:
    container_name: web
    build: ./frontend
    volumes:
      - ./frontend/:/web
      - /web/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  redis:
    container_name: redis-cont
    image: "redis:6.2.4-alpine"
    environment:
      - REDIS_PASSWORD=teste
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      # save redisearch data to your current working directory
      - ./redis-data:/data
    command:
      # # Save if 100 keys are added in every 10 seconds
      # - "--save 10 100"
      # Set password
      - "--requirepass teste"

  redisinsight: # redis db visualization dashboard
    container_name: redisinsight-cont
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  redis-data:
  redisinsight:
  api:
